import { Metadata } from 'next';
import './globals.css';

import { Providers } from '@/lib/providers';
import { Header } from '@/components/header';

export const metadata: Metadata = {
  title: 'Next+Auth+Plotly App',
  description: 'Generated by Ivan K',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="container mx-auto h-full flex flex-col px-4">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
